version: "3"

services:
  # Frontend
  frontend:
    container_name: frontend # Keep this the same with the service name for better compatibility with both Docker Swarm and Compose configurations
    build:
      context: .
      dockerfile: docker/development/Dockerfile.development
      args:
        PORT: ${PORT}
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
      NODE_ENV: development
