version: "3"
services:
  # Frontend
  frontend:
    container_name: frontend # Keep this the same with the service name for better compatibility with both Docker Swarm and Compose configurations
    build:
      context: .
      dockerfile: docker/prod/Dockerfile.prod
    restart: unless-stopped
    networks:
      application-network: # External network for accessing the backend application
    ports:
      - "${PORT}:80"
    environment:
      PORT: ${PORT}
      NODE_ENV: production
networks:
  application-network: # External network for accessing the backend application
    name: ${BACKEND_NETWORK}
    external: true
